[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@openzeppelin-upgrades/=lib/openzeppelin-contracts-upgradeable/'
]

gas_reports = ["*"]

optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"
